### ISSUE TITLE
ep_font_size/static/css/iframe.css  bug

### ISSUE THREAD

**Issue by yoonyoungkim** [JohnMcLear/ep_font_size#10]
I found your source a small bug.

ep_font_size/static/css/iframe.css

fs8{font-size:8px}; // -> fs8{font-size:8px;}
fs9{font-size:9px}; // -> fs9{font-size:9px;}
fs10{font-size:10px;}
fs11{font-size:11px;}
fs12{font-size:12px;}
fs13{font-size:13px;}
fs14{font-size:14px;}
fs15{font-size:15px;}
fs16{font-size:16px;}
fs17{font-size:17px;}
fs18{font-size:18px;}
fs19{font-size:19px;}
fs20{font-size:20px;}

this problem cause the font8, font9 is not wowrking.
Thanks.

**Comment by JohnMcLear** [comment]
Fixed w/ https://github.com/JohnMcLear/ep_font_size/commit/6df9bbf27abd7af275f1924d3442c195d39f47be tnx
